/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 29 04:50:26 GMT 2024
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FIND_IN_SORTED_ESTest extends FIND_IN_SORTED_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      int[] intArray0 = new int[8];
      intArray0[0] = 229;
      intArray0[1] = 1;
      intArray0[2] = 0;
      intArray0[3] = 1377;
      intArray0[4] = 0;
      intArray0[5] = 1;
      intArray0[6] = (-3651);
      intArray0[7] = 0;
      FIND_IN_SORTED.binsearch(intArray0, 1, 1, 0);
      FIND_IN_SORTED fIND_IN_SORTED0 = new FIND_IN_SORTED();
      FIND_IN_SORTED.binsearch(intArray0, 842, 0, 0);
      FIND_IN_SORTED.find_in_sorted(intArray0, 0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int[] intArray0 = new int[1];
      intArray0[0] = 948;
      FIND_IN_SORTED.find_in_sorted(intArray0, 948);
      FIND_IN_SORTED fIND_IN_SORTED0 = new FIND_IN_SORTED();
      FIND_IN_SORTED.binsearch(intArray0, 1, 0, 1);
      // Undeclared exception!
      try { 
        FIND_IN_SORTED.binsearch(intArray0, 1, (-1), 750);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int[] intArray0 = new int[1];
      intArray0[0] = 948;
      FIND_IN_SORTED.find_in_sorted(intArray0, 948);
      FIND_IN_SORTED fIND_IN_SORTED0 = new FIND_IN_SORTED();
      FIND_IN_SORTED.binsearch(intArray0, 1, 0, 1);
      FIND_IN_SORTED.find_in_sorted(intArray0, 948);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int[] intArray0 = new int[0];
      FIND_IN_SORTED.find_in_sorted(intArray0, 0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int[] intArray0 = new int[7];
      intArray0[0] = (-1735);
      intArray0[1] = (-4243);
      intArray0[2] = 1634;
      intArray0[3] = 0;
      intArray0[4] = (-1004);
      intArray0[5] = 348;
      intArray0[6] = 2966;
      FIND_IN_SORTED.find_in_sorted(intArray0, 2966);
      // Undeclared exception!
      try { 
        FIND_IN_SORTED.binsearch(intArray0, 1, 4224, (-16));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int[] intArray0 = new int[3];
      intArray0[0] = 946;
      intArray0[1] = 3246;
      intArray0[2] = 2;
      int int0 = 926;
      FIND_IN_SORTED.find_in_sorted(intArray0, 926);
      FIND_IN_SORTED.find_in_sorted(intArray0, 3246);
      // Undeclared exception!
      try { 
        FIND_IN_SORTED.binsearch(intArray0, 946, (-1), 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      // Undeclared exception!
      try { 
        FIND_IN_SORTED.find_in_sorted((int[]) null, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("FIND_IN_SORTED", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FIND_IN_SORTED fIND_IN_SORTED0 = new FIND_IN_SORTED();
      int[] intArray0 = new int[6];
      int int0 = 0;
      intArray0[0] = 0;
      int int1 = 0;
      intArray0[1] = 0;
      int int2 = (-908);
      intArray0[2] = (-908);
      intArray0[3] = 0;
      intArray0[4] = 190;
      intArray0[5] = 0;
      FIND_IN_SORTED.find_in_sorted(intArray0, 0);
      // Undeclared exception!
      try { 
        FIND_IN_SORTED.binsearch(intArray0, 0, 1, (-1390));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      int[] intArray0 = new int[6];
      intArray0[0] = 0;
      int int0 = FIND_IN_SORTED.find_in_sorted(intArray0, 0);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int[] intArray0 = new int[1];
      intArray0[0] = 1805;
      // Undeclared exception!
      try { 
        FIND_IN_SORTED.binsearch(intArray0, 5577, 1047, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      int[] intArray0 = new int[1];
      intArray0[0] = (-1366);
      FIND_IN_SORTED.binsearch(intArray0, (-1366), (-1366), (-1366));
      int int0 = FIND_IN_SORTED.binsearch(intArray0, (-1366), 0, 0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      int[] intArray0 = new int[7];
      intArray0[0] = (-4739);
      intArray0[1] = 1;
      intArray0[2] = 1;
      intArray0[3] = 2024;
      intArray0[4] = 2;
      intArray0[5] = 0;
      intArray0[6] = (-545);
      // Undeclared exception!
      try { 
        FIND_IN_SORTED.binsearch(intArray0, (-545), 2, (-545));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        FIND_IN_SORTED.binsearch((int[]) null, 2130, 2130, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
